In [1]:
import os
import pandas as pd
cul = pd.read_excel("culture.xlsx", encoding='utf-8')
eco = pd.read_excel("economy.xlsx", encoding='utf-8')
glo = pd.read_excel("global.xlsx", encoding='utf-8')
pol = pd.read_excel("politic.xlsx", encoding='utf-8')
soc = pd.read_excel("society.xlsx", encoding='utf-8')

# 데이터 라벨링

In [3]:
eco[0]=eco['title']
eco

,Unnamed: 0,title,0
0,0,"""하루 전화만 50통""…사생활 없어진 송파 헬리오시티","""하루 전화만 50통""…사생활 없어진 송파 헬리오시티"
1,1,"243만원, 287만원, 321만원…진짜 평균임금은 얼마야?","243만원, 287만원, 321만원…진짜 평균임금은 얼마야?"
2,2,"""집 산다는 사람 없다"" 매수지수 뚝…부동산 '안정 신호'","""집 산다는 사람 없다"" 매수지수 뚝…부동산 '안정 신호'"
3,3,"[르포]거제와 울산, 떠났던 배가 돌아온다","[르포]거제와 울산, 떠났던 배가 돌아온다"
4,4,상다리 휘어져야 조상에 대한 예의? 차례상에 대한 오해,상다리 휘어져야 조상에 대한 예의? 차례상에 대한 오해
...,...,...,...
10975,10975,다주택자 10년이상 보유주택 팔면 6월말까지 양도세 중과 배제,다주택자 10년이상 보유주택 팔면 6월말까지 양도세 중과 배제
10976,10976,영화 82편 '1초 전송'…삼성 초고속 D램 세계 첫 출시,영화 82편 '1초 전송'…삼성 초고속 D램 세계 첫 출시
10977,10977,"기아차, 신형 쏘렌토 3월 출시…티저 이미지 공개","기아차, 신형 쏘렌토 3월 출시…티저 이미지 공개"
10978,10978,"신종코로나, 결국 ‘제네시스’ 세웠다…그랜저는 증산키로","신종코로나, 결국 ‘제네시스’ 세웠다…그랜저는 증산키로"
10979,10979,아파트 하나에 10만명 청약하는 마당에…7만명도 문제 없었다는 황…,아파트 하나에 10만명 청약하는 마당에…7만명도 문제 없었다는 황…

In [4]:
cul2 = pd.DataFrame(cul[0])
cul2["label"] = 1

glo2 = pd.DataFrame(glo[0])
glo2["label"] = 2

pol2 = pd.DataFrame(pol[0])
pol2["label"] = 3

soc2 = pd.DataFrame(soc[0])
soc2["label"] = 4

eco2 = pd.DataFrame(eco[0])
eco2["label"] = 5

In [41]:
data = cul2.append(glo2)
data = data.append(pol2)
data = data.append(soc2)
data = data.append(eco2)
len(data)

data = data.rename(columns={0:'news'})
data
data_set = data.sample(frac=1).reset_index(drop=True)
data_set

                                           news  label
0               모리타니·말리···피랍 장씨, 위험경보 6개국 쭉 훑었다      2
1                예결위 파행날 올린 강기정 맥주샷… 한국당 "약올리나"      3
2              재계도 격앙 "北, 현대 돈으로 핵무기 완성하고 토사구팽"      5
3      EU·英, 브렉시트 4월12일로 연기…이후 '운명'은 英 하원 손에(종…      2
4                      올해 장마 '지각'…내륙 7월에 본격 장맛비      1
...                                         ...    ...
54895                  [영상] 영화 ‘기생충’ 이러다가 일 내겠네      1
54896     [Pick] 'PC방 살인' 김성수에 사형 구형하며 검사가 남긴 말      4
54897           미 남부 폭우로 8명 죽고 수십명 부상, 9만명 정전피해      2
54898       "2년치 이자 드릴게요"…청년 세입자 유혹하는 꼼수 전세 주의보      5
54899    금태섭, 공지영 향해 "'대통령이 하니까 무조건 찬성'은 좀 그렇다"      3

[54900 rows x 2 columns]

In [9]:
# import pandas as pd
# df = pd.DataFrame.from_records(data)
# df.to_csv('data.csv', index = False, header = True)

In [15]:
# # shuffle

# import csv
# import random
# import os
 
# # os.chdir("C:/Users\ICT01_21/Desktop/project(200204~200207)/Csv")
# file = open('data.csv', 'r', encoding='utf-8')
# line = file.readlines()
# random.shuffle(line)
# rcsv = csv.reader(line)
 
# file_write = open('data.csv', 'w', encoding='utf-8')
# wcsv = csv.writer(file_write)
 
# for i in rcsv:
#     try:
#         wcsv.writerow([i[0].strip(), i[1]])
#     except:
#         pass

In [13]:
# a = pd.read_csv("data.csv")
# a

                           폐암 전이 막고…고추의 건강 효과 5  1
0      ‘21세기 최악의 테러리스트’ 수괴 잃은 IS, 전 세계 테러리즘 소멸…  2
1       “20억 밍크원단 ‘홀라당’…돈이 불탄 것” 막막한 제일평화시장 상인…  5
2                       필리핀 마닐라 인근 관광지 따알 화산 분화  2
3                지구에서 가장 큰 꽃이 시체 썩는 냄새 풍기는 이유는?  1
4            추월 사고 쌍방과실?… 30일부터 추월차량이 ‘100% 과실’  5
...                                         ... ..
54835           임택근 별세로 임재범·손지창 가족사 재조명…조카는 성 김  1
54836           금수저도 부러워하는 행복주택?…LH 광고가 불쾌한 청년들  1
54837        알몸 여성, 상가서 '소화기 난사' 후 도주…경찰 뒤늦게 조사  4
54838        지적장애女 악몽, 죽어야 끝났다···'셰어하우스 살인'의 전말  4
54839     [종합] 한성주 근황, 아나운서→동영상 파문→원예치료전문가로 제2…  1

[54840 rows x 2 columns]

In [73]:
# from konlpy.tag import Kkma
# kkma = Kkma()
# kkma.pos(a)

TypeError: No matching overloads found for kr.lucypark.kkma.KkmaInterface.morphAnalyzer(DataFrame), options are:
	public java.util.List kr.lucypark.kkma.KkmaInterface.morphAnalyzer(java.lang.String) throws java.lang.Exception

	at JPMethod::findOverload(native\common\jp_method.cpp:242)
	at JPMethod::findOverload(native\common\jp_method.cpp:245)
	at JPMethod::invoke(native\common\jp_method.cpp:253)
	at PyJPMethod::__call__(native\python\pyjp_method.cpp:142)

In [72]:
# from konlpy.tag import Twitter

# twt = Twitter()
# tagging = twt.pos(a)
# tagging

C:\Users\ICT01_21\Anaconda3\envs\tf_test\lib\site-packages\konlpy\tag\_okt.py:16: UserWarning: "Twitter" has changed to "Okt" since KoNLPy v0.4.5.
  warn('"Twitter" has changed to "Okt" since KoNLPy v0.4.5.')

TypeError: No matching overloads found for kr.lucypark.okt.OktInterface.tokenize(DataFrame,java.lang.Boolean,java.lang.Boolean), options are:
	public java.util.List kr.lucypark.okt.OktInterface.tokenize(java.lang.String,java.lang.Boolean,java.lang.Boolean)

	at JPMethod::findOverload(native\common\jp_method.cpp:242)
	at JPMethod::findOverload(native\common\jp_method.cpp:245)
	at JPMethod::invoke(native\common\jp_method.cpp:253)
	at PyJPMethod::__call__(native\python\pyjp_method.cpp:142)

In [25]:
# from konlpy.tag import Twitter
# from gensim.models import Word2Vec
# import csv
 
# twitter = Twitter()
# category = ['문화', '세계', '정치', '사회', '경제']
# file = open("data.csv", 'r', encoding='utf-8')
# line = csv.reader(file)
# token = []
# embeddingmodel = []
 
# for i in line:
#     sentence = twitter.pos(i[0], norm=True, stem=True)
#     temp = []
#     temp_embedding = []
#     all_temp = []
#     for k in range(len(sentence)):
#         temp_embedding.append(sentence[k][0])
#         temp.append(sentence[k][0] + '/' + sentence[k][1])
#     all_temp.append(temp)
#     embeddingmodel.append(temp_embedding)
#     category_number_dic = {'문화' : 1, '세계' : 2, '정치' : 3, '사회' : 4, '경제' : 5}
#     all_temp.append(category_number_dic.get(category))
#     token.append(all_temp)
# print("토큰 처리 완료")
 
# embeddingmodel = []
# for i in range(len(token)):
#     temp_embeddingmodel = []
#     for k in range(len(token[i][0])):
#         temp_embeddingmodel.append(token[i][0][k])
#     embeddingmodel.append(temp_embeddingmodel)

# embedding = Word2Vec(embeddingmodel, size=300, window=5, min_count=10, iter=5, sg=1, max_vocab_size = 360000000)
# embedding.save('post.embedding')

TypeError: unhashable type: 'list'

# 데이터 나누기

In [27]:
import numpy as np
from sklearn.model_selection import train_test_split
train, test = train_test_split(data, test_size = 0.33, random_state = 42) # 테스트셋 3분의 1

In [28]:
print(train.shape)
print(test.shape)

(36783, 2)
(18117, 2)

In [29]:
train["label"] = pd.Categorical(train["label"])
train.groupby("label").count()

C:\Users\ICT01_21\Anaconda3\envs\tf_test\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

       news
label
1      7304
2      7377
3      7386
4      7353
5      7363

In [30]:
test.groupby("label").count()

       news
label
1      3676
2      3603
3      3594
4      3627
5      3617

# 명사 추출하여 TDM 생성

In [31]:
from konlpy.tag import Twitter
from sklearn.feature_extraction.text import CountVectorizer

def get_noun(text) :
    tokenizer = Twitter()
    nouns = tokenizer.nouns(text)
    return [n for n in nouns]

In [44]:
len(train["news"])

36783

In [47]:
cv = CountVectorizer(tokenizer=get_noun)
# for i in range(len(train["news"])):
cv.fit_transform(train["news"])

cv.vocabulary_

{'유승민': 12879,
 '대구': 3772,
 '간다': 190,
 '출마': 16881,
 '한국': 18987,
 '도로': 4107,
 '친': 17037,
 '스마트': 9929,
 '리빙': 5003,
 '반점': 6590,
 '고구마': 980,
 '세': 9204,
 '이세돌': 13402,
 '은퇴': 13090,
 '알파': 10999,
 '인간': 13623,
 '호날두': 19646,
 '불똥': 7783,
 '알베르토': 10986,
 '왜': 12252,
 '감독': 256,
 '말': 5269,
 '통역': 17842,
 '댓글': 3997,
 '테러': 17733,
 '승기': 10090,
 '세대': 9218,
 '세단': 9217,
 '수': 9609,
 '중형': 15638,
 '럭셔리': 4777,
 '타깃': 17516,
 '여성': 11580,
 '신림동': 10343,
 '강간미수': 325,
 '솜방망이': 9527,
 '처벌': 16347,
 '육군': 12992,
 '공군': 1209,
 '해병대': 19264,
 '총수': 16692,
 '진격': 15908,
 '합참': 19177,
 '법원': 7075,
 '과녁': 1340,
 '여교사': 11550,
 '활': 19950,
 '교감': 1512,
 '강등': 353,
 '정당': 14826,
 '노트르담': 3282,
 '부녀': 7517,
 '화재': 19872,
 '직전': 15891,
 '사진': 8395,
 '주인공': 15451,
 '트럼프': 17962,
 '김정은': 2554,
 '변화': 7199,
 '기대': 2202,
 '비핵화': 8057,
 '향': 19395,
 '한강': 18981,
 '시신': 10206,
 '피의자': 18758,
 '신상': 10362,
 '공개': 1199,
 '카메라': 17136,
 '장대': 14243,
 '호': 19637,
 '우한': 12505,
 '교민': 1527,
 '긴급': 2333,
 '연결': 11673,
 '짐': 16007,
 '몸': 5803,
 '격리': 739,
 '조치': 15231,
 '연': 11669,
 '판매': 18172,
 '중단': 15564,
 '콜마': 17378,
 '불매': 7792,
 '계속': 948,
 '문재인': 6033,
 '정부': 14873,
 '어차피': 11354,
 '달': 3645,
 '이면': 13308,
 '끝': 2771,
 '날': 2930,
 '고음': 1082,
 '코란도': 17310,
 '편': 18351,
 '반세기': 6573,
 '차': 16129,
 '젠': 15094,
 '미래': 6158,
 '단독': 3598,
 '누가': 3376,
 '삼성': 8546,
 '경영': 863,
 '스타': 9984,
 '를': 4976,
 '망가뜨렸': 5312,
 '한국인': 18992,
 '억류': 11364,
 '구출': 1688,
 '프랑스군': 18661,
 '명': 5573,
 '전사': 14616,
 '국민': 1747,
 '눈높이': 3400,
 '괴리': 1502,
 '주시': 15428,
 '낙마': 2861,
 '베르나르': 7108,
 '포콩': 18493,
 '방탄소년단': 6796,
 '뮤비': 6118,
 '내': 3054,
 '작품': 14155,
 '영감': 11828,
 '입장': 13956,
 '문': 6005,
 '발표': 6688,
 '술잔': 9873,
 '거부': 581,
 '직원': 15883,
 '사이다': 8353,
 '준': 15501,
 '상사': 8625,
 '마디': 5094,
 '소프트뱅크': 9426,
 '투자': 17928,
 '후': 20093,
 '폭풍': 18549,
 '손실': 9494,
 '종합': 15336,
 '북한': 7680,
 '미사일': 6180,
 '오보에': 12032,
 '전문가': 14599,
 '전쟁': 14675,
 '나흘': 2854,
 '또': 4641,
 '함흥': 19151,
 '동해': 4386,
 '미상': 6181,
 '발사체': 6658,
 '발': 6613,
 '발사': 6657,
 '여행객': 11626,
 '감소': 270,
 '열도': 11786,
 '미스': 6199,
 '오키나와': 12087,
 '공항': 1322,
 '환영': 19936,
 '행사': 19367,
 '오열': 12056,
 '유족': 12929,
 '한숨': 19048,
 '쉰': 9893,
 '길': 2340,
 '멋': 5468,
 '시드니': 10161,
 '하늘': 18844,
 '호주': 19685,
 '여행자': 11630,
 '닛산': 3489,
 '시장': 10222,
 '철수': 16441,
 '검토': 681,
 '태풍': 17673,
 '바': 6346,
 '이루': 13296,
 '수증기': 9769,
 '한반도': 19028,
 '유입': 12915,
 '전국': 14545,
 '비': 7938,
 '멕시코': 5517,
 '위': 12710,
 '추락': 16807,
 '후진': 20130,
 '자동차': 14013,
 '산업': 8472,
 '스마트폰': 9930,
 '최대': 16714,
 '밝기': 6695,
 '각막': 168,
 '구멍': 1624,
 '개': 447,
 '박정희': 6497,
 '선': 8955,
 '군복': 1827,
 '선글라스': 8965,
 '눈': 3396,
 '일본': 13782,
 '무역': 5943,
 '보복': 7310,
 '상품': 8688,
 '이사회': 13365,
 '상정': 8669,
 '오늘': 11987,
 '논의': 3315,
 '매출': 5391,
 '가장': 118,
 '프랜차이즈': 18664,
 '치킨': 17031,
 '집': 16010,
 '세계': 9206,
 '금융허브': 2122,
 '서울': 8888,
 '건물': 632,
 '주': 15365,
 '김부겸': 2435,
 '박원순': 6478,
 '광화문': 1492,
 '광장': 1482,
 '거듭': 563,
 '반': 6534,
 '불법이민': 7802,
 '피난처': 18723,
 '도시': 4145,
 '이송': 13409,
 '정가': 14805,
 '논란': 3308,
 '손학규': 9513,
 '쓴소리': 10657,
 '기분': 2235,
 '것': 687,
 '황교안': 19973,
 '좀': 15286,
 '최정훈': 16766,
 '아버지': 10737,
 '사업': 8331,
 '전혀': 14714,
 '관련': 1408,
 '법적': 7078,
 '대응': 3892,
 '원금': 12601,
 '피해자': 18777,
 '집단소송': 16022,
 '제기': 15011,
 '유정': 12925,
 '전남편': 14561,
 '변태': 7192,
 '성관계': 9095,
 '요구': 12333,
 '이': 13234,
 '비극': 7947,
 '건강': 620,
 '좌우': 15345,
 '습관': 10079,
 '동학': 4385,
 '농민': 3338,
 '혁명': 19520,
 '기념일': 2197,
 '국무회의': 1744,
 '의결': 13170,
 '사연': 8334,
 '뉴스': 3428,
 '퇴근': 17882,
 '카톡': 17161,
 '안': 10878,
 '싸가지': 10592,
 '후배': 20108,
 '어쩌': 11349,
 '벼랑': 7151,
 '이재용': 13505,
 '시계': 10134,
 '제로': 15027,
 '아이': 10781,
 '비닐봉지': 7953,
 '속': 9440,
 '베트남': 7129,
 '극한': 2031,
 '통학': 17869,
 '화제': 19873,
 '홍콩': 19807,
 '나': 2782,
 '도전': 4171,
 '처음': 16355,
 '아들': 10693,
 '웜': 12687,
 '비어': 8013,
 '부모': 7543,
 '응징': 13163,
 '법': 7058,
 '박쥐': 6504,
 '배설물': 6839,
 '동굴': 4290,
 '남성': 2983,
 '구조': 1673,
 '트와이스': 17983,
 '효': 20079,
 '사람': 8244,
 '마주': 5162,
 '감정': 289,
 '이야기': 13438,
 '사과': 8216,
 '생각': 8759,
 '직감': 15859,
 '결과': 765,
 '영국': 11833,
 '기차역': 2310,
 '대학': 3959,
 '은행': 13096,
 '폭발물': 18524,
 '의심': 13202,
 '우편물': 12501,
 '발견': 6617,
 '서소문': 8874,
 '사진관': 8397,
 '매년': 5356,
 '곳': 1190,
 '시궁창': 10142,
 '오명': 12026,
 '보': 7250,
 '애나': 11073,
 '버닝썬': 6971,
 '엑스터시': 11510,
 '투약': 17922,
 '추방': 16814,
 '불복': 7809,
 '똑': 4646,
 '기자': 2286,
 '꿀': 2751,
 '정보': 14862,
 '주방': 15411,
 '삼겹살': 8535,
 '기름': 2214,
 '닭강정': 3673,
 '거짓': 609,
 '주문': 15406,
 '공론': 1228,
 '업주': 11437,
 '블루': 7931,
 '보틀': 7364,
 '호점': 19684,
 '려고': 4848,
 '연차': 11753,
 '문정': 6035,
 '권판': 1922,
 '부자': 7594,
 '검찰': 677,
 '양': 11202,
 '만찬': 5253,
 '속보': 9451,
 '이란': 13290,
 '보좌': 7353,
 '관': 1388,
 '미군기지': 6134,
 '대상': 3855,
 '군사': 1832,
 '때': 4610,
 '거': 553,
 '영업': 11865,
 '전화': 14718,
 '번호': 7022,
 '어찌': 11353,
 '한일': 19068,
 '협력': 19589,
 '우려': 12432,
 '실망': 10462,
 '미아': 6212,
 '볼턴': 7456,
 '미국': 6129,
 '자': 13981,
 '회담': 20034,
 '선호': 9032,
 '안해': 10961,
 '중러': 15574,
 '대북': 3850,
 '제재': 15070,
 '황홀': 20019,
 '언론': 11380,
 '박항서': 6524,
 '매직': 5385,
 '특필': 18031,
 '퇴직': 17893,
 '임원': 13882,
 '눈덩이': 3401,
 '판문점': 18177,
 '회': 20024,
 '트윗': 17988,
 '제안': 15047,
 '어제': 11343,
 '라디오': 4689,
 '방송': 6752,
 '출연': 16897,
 '정두언': 14833,
 '전': 14528,
 '의원': 13210,
 '사망': 8264,
 '소': 9302,
 '땅콩주택': 4609,
 '폭': 18510,
 '평': 18375,
 '열풍': 11805,
 '조국': 15113,
 '구역질': 1657,
 '비난': 7949,
 '반일': 6584,
 '종족': 15332,
 '주의': 15447,
 '홍준표': 19802,
 '이건': 13236,
 '펭수': 18350,
 '다이어리': 3557,
 '살': 8496,
 '입처': 13964,
 '가격': 3,
 '임지연': 13891,
 '하와이': 18892,
 '피부색': 18744,
 '상상': 8627,
 '못': 5820,
 '배터리': 6877,
 '동맹': 4307,
 '완성': 12205,
 '구광모': 1596,
 '빅딜': 8071,
 '최태원': 16780,
 '출격': 16868,
 '폰': 18553,
 '듀얼': 4478,
 '스크린': 9977,
 '통': 17815,
 '국내': 1726,
 '신종': 10410,
 '코로나': 17313,
 '확진': 19906,
 '환자': 19941,
 '태국': 17645,
 '여행': 11624,
 '지난달': 15717,
 '입국': 13913,
 '최악': 16742,
 '기질': 2308,
 '언제': 11390,
 '중국': 15552,
 '먼지': 5461,
 '자유': 14072,
 '해산': 19267,
 '청와대': 16510,
 '청원': 16513,
 '민주당': 6290,
 '불': 7746,
 '국경': 1720,
 '폐쇄': 18428,
 '시진핑': 10230,
 '위문': 12725,
 '서한': 8924,
 '펫': 18345,
 '톡톡': 17809,
 '윤균상': 13016,
 '유기묘': 12798,
 '입양': 13949,
 '한눈': 19005,
 '팩트': 18255,
 '체크': 16567,
 '군': 1811,
 '사령관': 8248,
 '드론': 4493,
 '피격': 18714,
 '실제': 10499,
 '영상': 11852,
 '확인': 19900,
 '마음': 5142,
 '대부분': 3849,
 '부정': 7604,
 '지금': 15709,
 '부인': 7591,
 '구속': 1647,
 '사퇴': 8419,
 '목소리': 5759,
 '하노이': 18842,
 '공장': 1289,
 '박닌': 6426,
 '간': 186,
 '김창선': 2594,
 '김성태': 2462,
 '딸': 4593,
 '이력서': 13294,
 '직접': 15892,
 '일': 13743,
 '주말': 15398,
 '사고': 8213,
 '정관': 14815,
 '수술': 9713,
 '부': 7499,
 '날씨': 2942,
 '초미세먼지': 16603,
 '주의보': 15448,
 '해제': 19307,
 '한낮': 19004,
 '봄': 7459,
 '야구': 11129,
 '교실': 1540,
 '흉기': 20199,
 '난동': 2896,
 '코치': 17348,
 '발차기': 6679,
 '제압': 15048,
 '공격': 1201,
 '작전': 14151,
 '개시': 487,
 '취소': 16963,
 '쌀': 10607,
 '지원': 15794,
 '대화': 3983,
 '재개': 14354,
 '마중': 5163,
 '물': 6054,
 '총선': 16690,
 '출구조사': 16871,
 '보수당': 7321,
 '압승': 11034,
 '석': 8933,
 '확보': 19896,
 '전망': 14589,
 '커튼': 17238,
 '머리': 5439,
 '신분증': 10357,
 '얼굴': 11393,
 '추진': 16832,
 '당신': 3737,
 '거래': 565,
 '준비': 15506,
 '민경욱': 6263,
 '김정숙': 2551,
 '여사': 11577,
 '악수': 10863,
 '천장': 16410,
 '물새': 6083,
 '송파': 9571,
 '헬리': 19509,
 '시티': 10245,
 '에어컨': 11482,
 '주민': 15409,
 '고통': 1115,
 '재계': 14362,
 '격앙': 742,
 '현대': 19530,
 '돈': 4242,
 '핵무기': 19325,
 '토사': 17786,
 '팽': 18275,
 '아빠': 10745,
 '누구': 3377,
 '암컷': 11015,
 '수족관': 9763,
 '새끼': 8706,
 '상어': 8647,
 '본기': 7424,
 '탄탄': 17585,
 '제네시스': 15014,
 '체구': 16536,
 '존재': 15268,
 '감': 248,
 '코드': 17308,
 '집착': 16048,
 '전문': 14598,
 '인사': 13670,
 '밤': 6697,
 '관심': 1427,
 '폭발': 18523,
 '나이트': 2835,
 '워': 12581,
 '참여': 16257,
 '방법': 6740,
 '김태호': 2608,
 '뭐': 6110,
 '시청률': 10236,
 '역시': 11655,
 '신선': 10366,
 '반도체': 6553,
 '공급': 1212,
 '중지': 15630,
 '시기': 10147,
 '면밀': 5545,
 '조사': 15153,
 '바로': 6371,
 '조선': 15160,
 '파시즘': 18117,
 '사나': 8231,
 '발끈': 6624,
 '김무성': 2409,
 '고백': 1036,
 '새누리': 8709,
 '살생': 8513,
 '명단': 5578,
 '한인': 19065,
 '패션': 18229,
 '업체': 11438,
 '포에버': 18480,
 '대규모': 3779,
 '감원': 283,
 '등': 4516,
 '구조조정': 1677,
 '착수': 16205,
 '어린이날': 11312,
 '최고': 16709,
 '도': 4081,
 '한여름': 19055,
 '더위': 4011,
 '미세먼지': 6185,
 '이틀': 13581,
 '만원': 5244,
 '강북': 367,
 '이하': 13584,
 '아파트': 10836,
 '상승': 8641,
 '대감': 3760,
 '매물': 5372,
 '카페': 17164,
 '김밥': 2421,
 '알바생': 10983,
 '문제': 6038,
 '헉스': 19454,
 '유시민': 12883,
 '독기': 4198,
 '평가': 18376,
 '성공': 9092,
 '온라인': 12133,
 '의사': 13194,
 '월급': 12667,
 '자료': 14018,
 '추적': 16829,
 '이참': 13556,
 '결기': 766,
 '파기': 18084,
 '공식': 1269,
 '에이미': 11487,
 '이제야': 13524,
 '입': 13906,
 '충격': 16924,
 '이유': 13479,
 '증거': 15671,
 '박': 6412,
 '현영': 19549,
 '글로벌': 2065,
 '인사이트': 13673,
 '중': 15528,
 '협상': 19591,
 '돌연': 4265,
 '결렬': 768,
 '뒤': 4447,
 '회사': 20043,
 '가기': 14,
 '구': 1587,
 '서민': 8858,
 '살이': 8518,
 '공감': 1198,
 '불합격': 7853,
 '깜깜': 2674,
 '통보': 17832,
 '타': 17509,
 '취준생': 16972,
 '저자': 14477,
 '논문': 3310,
 '고': 968,
 '땐': 4618,
 '의학': 13227,
 '생물학': 8782,
 '맏': 5267,
 '며느리': 5534,
 '올케': 12163,
 '형수': 19620,
 '우리': 12435,
 '엄마': 11410,
 '늘': 3453,
 '혼자': 19738,
 '더': 3999,
 '금리': 2091,
 '틈새': 18042,
 '볼': 7451,
 '접대': 14786,
 '의혹': 13232,
 '양현석': 11279,
 '메일': 5513,
 '아베': 10738,
 '대통령': 3943,
 '언행': 11391,
 '신사': 10359,
 '자주': 14095,
 '허위': 19442,
 '사실': 8322,
 '유포': 12963,
 '혐의': 19583,
 '수사': 9684,
 '레오': 4813,
 '발언': 6666,
 '팽팽': 18277,
 '긴장': 2338,
 '호르무즈': 19656,
 '해협': 19322,
 '자전거': 14089,
 '횡단': 20072,
 '나선': 2818,
 '청년': 16483,
 '교통사고': 1570,
 '인기': 13642,
 '개그맨': 456,
 '제': 15004,
 '유튜버': 12961,
 '무명': 5904,
 '반란': 6556,
 '태극기': 17650,
 '부대': 7523,
 '장외': 14315,
 '당내': 3721,
 '전대': 14568,
 '부산': 7553,
 '조현병': 15241,
 '친누나': 17042,
 '무참': 5979,
 '살해': 8529,
 '질': 15984,
 '오염': 12057,
 '지역': 15782,
 '전역': 14645,
 '확대': 19894,
 '후베이성': 20110,
 '권고': 1893,
 '찬': 16212,
 '바람': 6368,
 '종일': 15325,
 '가끔': 17,
 '구름': 1621,
 '경북': 841,
 '동해안': 4388,
 '유동현': 12818,
 '제주': 15075,
 '바다': 6356,
 '주검': 15376,
 '송': 9530,
 '병기': 7221,
 '업무': 11431,
 '수첩': 9776,
 '산재': 8478,
 '병원': 7240,
 '좌초': 15350,
 '전라': 14577,
 '강진서': 421,
 '최고급': 16710,
 '고려청자': 1011,
 '다량': 3509,
 '출토': 16909,
 '몰락': 5787,
 '파나소닉': 18086,
 '최저임금': 16763,
 '과속': 1351,
 '부메랑': 7542,
 '비정규직': 8027,
 '공화국': 1326,
 '노': 3182,
 '믹스': 6254,
 '해리': 19249,
 '왕자': 12244,
 '부부': 7546,
 '캐나다': 17190,
 '이주': 13530,
 '독설': 4222,
 '정작': 14940,
 '별로': 7208,
 '죽음': 15498,
 '통증': 17856,
 '주사': 15416,
 '아내': 10680,
 '민간': 6258,
 '분양': 7723,
 '칼': 17173,
 '빼': 8160,
 '강남': 343,
 '재건축': 14358,
 '첫': 16466,
 '금호': 2138,
 '박삼구': 6446,
 '회장': 20058,
 '복귀': 7385,
 '산은': 8475,
 '요청': 12362,
 '이륙': 13298,
 '직후': 15906,
 '카자흐': 17152,
 '항공기': 19194,
 '패스트': 18235,
 '트랙': 17954,
 '저지': 14483,
 '투쟁': 17931,
 '지난해': 15719,
 '국민소득': 1748,
 '돌파': 4272,
 '체감': 16532,
 '글쎄': 2069,
 '조현': 15239,
 '수령': 9656,
 '내용': 3090,
 '짜증': 16078,
 '계엄': 958,
 '문건': 6006,
 '실무': 10464,
 '진': 15907,
 '진술': 15933,
 '시대': 10157,
 '마이': 5146,
 '너리': 3133,
 '티': 18044,
 '무슬림': 5930,
 '일삼': 13798,
 '종교': 15294,
 '이학수': 13586,
 '다스': 3532,
 '소송': 9376,
 '증언': 15689,
 '여러': 11564,
 '차례': 16150,
 '욕설': 12370,
 '셀트리온': 9283,
 '종근당': 15295,
 '양재': 11251,
 '유방암': 12853,
 '신약': 10380,
 '복용': 7405,
 '수영복': 9731,
 '심사': 10541,
 '어우동': 11336,
 '쇼': 9595,
 '미스코리아': 6202,
 '한복': 19034,
 '무려': 5887,
 '로또복권': 4868,
 '당첨번호': 3748,
 '동성애자': 4335,
 '에이즈': 11490,
 '지난날': 15716,
 '청산': 16501,
 '강사': 369,
 '사위': 8347,
 '조운': 15202,
 '고려병원': 1009,
 '이사장': 13362,
 '별세': 7212,
 '게스트하우스': 694,
 '가스': 79,
 '어린이': 11311,
 '중상': 15593,
 '거리': 572,
 '외국': 12270,
 '성매매': 9121,
 '기승': 2258,
 '무더기': 5879,
 '적발': 14507,
 '공기': 1214,
 '비상조치': 7996,
 '고글': 982,
 '권총': 1920,
 '일베': 13779,
 '회원': 20052,
 '이춘': 13565,
 '재': 14352,
 '신발': 10348,
 '사이즈': 8362,
 '최초': 16778,
 '골든글로브': 1154,
 '오른': 12012,
 '기생충': 2245,
 '후보': 20111,
 '까닭': 2666,
 '인터뷰': 13728,
 '구도': 1612,
 '쉘리': 9891,
 '권혁수': 1927,
 '등뼈': 4529,
 '찜': 16126,
 '알바': 10981,
 '그': 1975,
 '디': 4547,
 '수출': 9778,
 '기업': 2268,
 '고심': 1061,
 '엑스': 11507,
 '프듀': 18649,
 '조작': 15211,
 '해체': 19314,
 '리본': 4999,
 '해군': 19239,
 '총장': 16694,
 '노무현': 3225,
 '직설': 15877,
 '검사': 667,
 '적진': 14525,
 '비행기': 8059,
 '개월': 492,
 '아기': 10676,
 '선물': 8976,
 '기장': 2290,
 '군청': 1856,
 '기장역': 2291,
 '전차': 14689,
 '선로': 8973,
 '운행중단': 12544,
 '추문': 16812,
 '약혼': 11195,
 '파혼': 18158,
 '마약': 5133,
 '박유천': 6479,
 '황하나': 20014,
 '주렁주렁': 15391,
 '말리': 5286,
 '촌리': 16657,
 '곶감': 1331,
 '전설': 14621,
 '명보': 5594,
 '위해': 12768,
 '단': 3584,
 '코어': 17338,
 '근력': 2038,
 '장': 14218,
 '경제': 883,
 '안보': 10916,
 '국': 1706,
 '취급': 16958,
 '이번': 13338,
 '버버리': 6981,
 '자살': 14044,
 '매': 5349,
 '명품': 5628,
 '브랜드': 7889,
 '싸구려': 10593,
 '행태': 19393,
 '탄생': 17573,
 '생활': 8813,
 '검정': 674,
 '지리': 15735,
 '교과서': 1514,
 '독도': 4201,
 '땅': 4600,
 '이웃': 13474,
 '송중기': 9565,
 '송혜교': 9578,
 '결혼': 806,
 '파경': 18078,
 '이혼': 13603,
 '조정': 15214,
 '절차': 14749,
 '란': 4730,
 '헤파': 19501,
 '필터': 18806,
 '지연': 15787,
 '곤혹': 1142,
 '지하철': 15849,
 '항공': 19192,
 '결항': 804,
 '시위': 10218,
 '마비': 5114,
 '포커스': 18492,
 '구몬': 1628,
 '노노': 3189,
 '재팬': 14429,
 '불매운동': 7793,
 '엉덩이': 11441,
 '절반': 14740,
 '노출': 3275,
 '황': 19968,
 '대헌': 3978,
 '바지': 6399,
 '임효준': 13904,
 '동생': 4328,
 '처': 16337,
 '위장': 12752,
 '수치심': 9780,
 '호소': 19666,
 '김용균': 2515,
 '발전': 6673,
 '정비': 14874,
 '근로자': 2042,
 '계약': 952,
 '기간': 2177,
 '나경원': 2785,
 '어머니': 11316,
 '증인': 15694,
 '채택': 16322,
 '양보': 11225,
 '민주': 6289,
 '이상': 13370,
 '변': 7160,
 '결코': 797,
 '과거': 1334,
 '모두': 5657,
 '금지': 2128,
 '마스크': 5125,
 '방문': 6734,
 '북미': 7661,
 '관계': 1392,
 '산': 8443,
 ...}

In [48]:
len(cv.vocabulary_)

20300

In [56]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.linear_model import SGDClassifier
from sklearn.pipeline import Pipeline

text_clf_svm = Pipeline([('vect', CountVectorizer(tokenizer=get_noun)),
                        ('tfidf', TfidfTransformer()),
                        ('clf-svm', SGDClassifier(loss='hinge', penalty='l2', alpha=1e-3, random_state=42))])

text_clf_svm = text_clf_svm.fit(train["news"], train["label"])

In [54]:
predicted_svm = text_clf_svm.predict(test["news"])
np.mean(predicted_svm == test["label"])

0.7046972456808522