In [ ]:
for col in P_GRDP.columns:
    if col == "세대수" or col == "GRDP(단위 : 백만원)":
        del P_GRDP[col]
print(P_GRDP)

In [16]:
import pandas as pd
inpeople = pd.read_csv("전처리완료데이터.csv")
inpeople.iloc[:, 1:2]
del inpeople["Unnamed: 0"]
df = inpeople.iloc[:, 1:]
df["카드매출액"] = df["카드매출액"]*0.01*2884
df

       인구    세대수  사업체수      카드매출액   wifi사용자수
0   50137  19526  4988  199.25556  3076786.0
1   43217  19336  4681  327.42052  3126565.0
2   56223  21026  4318  234.67108  4843117.0
3   36550  15563  2232  127.50164   939748.0
4   34684  13187  2173   96.58516  2563285.0
5   25003  10204  2065   84.53004   450801.0
6   34321  13337  1909   86.23160  1826291.0
7   24718  10538  1688   85.33756  1677427.0
8   23094   9924  1655   60.01604   729594.0
9   24163   8933  1651   29.07072  1517329.0
10  16283   7670  1561   48.79728   565136.0
11  25391   9542  1516   47.58600  1346005.0
12   7989   7851  1510   49.51828  1706470.0
13  17180   7753  1484   80.03100  1306846.0
14  14345   5952  1385   31.86820   919731.0
15   2993   1623  1329   45.71140  1054688.0
16   3984   2124  1277   26.34534    79420.0
17  12824   5922  1140   50.84492   882465.0
18  21741   8167  1106   41.09700   994026.0
19  19778   8438  1070   57.99724   501055.0
20   8662   4161  1025   60.21792  1223869.0
21  15673   6456  1021  238.21840  1658664.0
22  12537   6033   966   80.98272  1003790.0
23   3257   1412   952   30.22432   141161.0
24  14906   5565   924   53.12328   300518.0
25  25153   9273   857   44.81736   675844.0
26   7610   3543   784   19.64004   812415.0
27   9857   4235   767   46.83616  1018933.0
28  11482   5155   721   63.21728  1151592.0
29   3657   1921   690   33.23810  1640001.0
30  14156   5844   688   62.20788  1691605.0
31   9447   4657   637   23.50460   296704.0
32   2444   1342   587   26.34534  1640000.0
33  10697   4240   492    6.89276  1196272.0
34  13930   6089   491   31.11836   170659.0
35   5478   2430   457   33.25252   502605.0
36   4414   1985   419   87.18332   628036.0
37   5027   2088   363   70.12446     8907.0
38   1892    999   278   13.43944   156445.0
39   5396   2262   278   10.15168   162734.0
40   4654   1829   272   14.13160   114543.0
41   4936   2094   257   21.22624   411600.0
42   2149   1049   212    3.48964        0.0

In [17]:
df["배출량"] = df["인구"]*2
df

       인구    세대수  사업체수      카드매출액   wifi사용자수     배출량
0   50137  19526  4988  199.25556  3076786.0  100274
1   43217  19336  4681  327.42052  3126565.0   86434
2   56223  21026  4318  234.67108  4843117.0  112446
3   36550  15563  2232  127.50164   939748.0   73100
4   34684  13187  2173   96.58516  2563285.0   69368
5   25003  10204  2065   84.53004   450801.0   50006
6   34321  13337  1909   86.23160  1826291.0   68642
7   24718  10538  1688   85.33756  1677427.0   49436
8   23094   9924  1655   60.01604   729594.0   46188
9   24163   8933  1651   29.07072  1517329.0   48326
10  16283   7670  1561   48.79728   565136.0   32566
11  25391   9542  1516   47.58600  1346005.0   50782
12   7989   7851  1510   49.51828  1706470.0   15978
13  17180   7753  1484   80.03100  1306846.0   34360
14  14345   5952  1385   31.86820   919731.0   28690
15   2993   1623  1329   45.71140  1054688.0    5986
16   3984   2124  1277   26.34534    79420.0    7968
17  12824   5922  1140   50.84492   882465.0   25648
18  21741   8167  1106   41.09700   994026.0   43482
19  19778   8438  1070   57.99724   501055.0   39556
20   8662   4161  1025   60.21792  1223869.0   17324
21  15673   6456  1021  238.21840  1658664.0   31346
22  12537   6033   966   80.98272  1003790.0   25074
23   3257   1412   952   30.22432   141161.0    6514
24  14906   5565   924   53.12328   300518.0   29812
25  25153   9273   857   44.81736   675844.0   50306
26   7610   3543   784   19.64004   812415.0   15220
27   9857   4235   767   46.83616  1018933.0   19714
28  11482   5155   721   63.21728  1151592.0   22964
29   3657   1921   690   33.23810  1640001.0    7314
30  14156   5844   688   62.20788  1691605.0   28312
31   9447   4657   637   23.50460   296704.0   18894
32   2444   1342   587   26.34534  1640000.0    4888
33  10697   4240   492    6.89276  1196272.0   21394
34  13930   6089   491   31.11836   170659.0   27860
35   5478   2430   457   33.25252   502605.0   10956
36   4414   1985   419   87.18332   628036.0    8828
37   5027   2088   363   70.12446     8907.0   10054
38   1892    999   278   13.43944   156445.0    3784
39   5396   2262   278   10.15168   162734.0   10792
40   4654   1829   272   14.13160   114543.0    9308
41   4936   2094   257   21.22624   411600.0    9872
42   2149   1049   212    3.48964        0.0    4298

In [18]:
from patsy import dmatrices
import statsmodels.api as sm
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [19]:
features = '인구+세대수+사업체수+카드매출액+wifi사용자수'

In [20]:
y, x = dmatrices("배출량~"+features, data = df, return_type="dataframe")

vif = [variance_inflation_factor(x.values, i) for i in range(x.shape[1])]
result = sm.OLS(y,x).fit()

In [21]:
print(result.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                    배출량   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 1.123e+30
Date:                Tue, 21 Jan 2020   Prob (F-statistic):               0.00
Time:                        16:10:20   Log-Likelihood:                 946.06
No. Observations:                  43   AIC:                            -1880.
Df Residuals:                      37   BIC:                            -1870.
Df Model:                           5
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept  -6.912e-11   1.96e-11     -3.533      0.001   -1.09e-10   -2.95e-11
인구             2.0000   5.03e-15   3.98e+14      0.000       2.000       2.000
세대수          9.77e-15   1.43e-14      0.683      0.499   -1.92e-14    3.88e-14
사업체수        2.309e-14   2.79e-14      0.827      0.414   -3.35e-14    7.97e-14
카드매출액      -3.553e-13   2.93e-13     -1.212      0.233   -9.49e-13    2.39e-13
wifi사용자수    7.893e-17   2.01e-17      3.932      0.000    3.83e-17     1.2e-16
==============================================================================
Omnibus:                       17.674   Durbin-Watson:                   1.156
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               22.406
Skew:                          -1.357   Prob(JB):                     1.36e-05
Kurtosis:                       5.267   Cond. No.                     2.55e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.55e+06. This might indicate that there are
strong multicollinearity or other numerical problems.